# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a780ba50b43443c06356dad46ecbda866e1cf17d7167955499ba4d2ee0ff23851bb2962d62b51020490360d53debe7e0d83c011105fdd250beb1fc81fde4929

test:
  secret_key_base: afd37d5bff8c18c267c51ea4fa5697ee1991b37c8de597a34dda06ad2f40602eab3ae0574ed4e5c0c7a93d12bcf6fac9de8ad7a38ea3516560c88ee5bc870185

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
